### ISSUE TITLE
Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead

### ISSUE THREAD

**Issue by Muhamed-Hamid** [haya14busa/action-cond#15]
Hi, 

I have this after last update

`Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')`

**Comment by scherroman** [comment]
Also got the error `Error: The runs.using key in action.yml must be one of: [composite docker node12], got node16` when running locally with act.

**Comment by seanoh1989** [comment]
bump!

**Comment by haya14busa** [comment]
Fixed by #23
