### ISSUE TITLE
The set-output command is deprecated

### ISSUE THREAD

**Issue by mquinzin** [haya14busa/action-cond#17]
Hi, when running the action I see several messages like this:

The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Do you plan to provide a new version using non deprecated command soon ?
Thx.

**Comment by illera88** [comment]
Same thing here

**Comment by vkatsuba** [comment]
Same issue.

**Comment by edoapra** [comment]
Try
```
      - uses: haya14busa/action-cond@dependabot/npm_and_yarn/actions/core-1.9.1
```
https://github.com/haya14busa/action-cond/commit/cd317ee178c1c2bc4602830c649929a1a145be04
