### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by JaskRendix** [haya14busa/action-cond#22]
Hi, I hope everything is fine. I got this warning.

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: haya14busa/action-cond@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
`
 Have a nice day!

**Comment by batica81** [comment]
It would be really nice if node version is bumped, those warnings are annoying.
